#!/usr/bin/env perl

use strict;
use warnings;
use Crypt::PasswdMD5;

sub usage(){
    return "${0} PASSWORD";
}

if(($#ARGV + 1) != 1)
{
    print STDERR usage();
    exit 1;
}

my $password = $ARGV[0];

print unix_md5_crypt($password);
