#!/usr/bin/env perl

use strict;
use warnings;
use Apache::Htpasswd;

use Getopt::Std;

sub usage(){
    return "${0} [-s] [-p PASSWORD] [-v PASSWORD] -u USERNAME FILE\n";
}

our($opt_s, $opt_p, $opt_v, $opt_u);

print "@ARGV\n";

if(!getopts('sp:v:u:'))
{
    print STDERR usage();
    exit 1;
}

print "@ARGV\n";

my $file = $ARGV[0];

print "$opt_s $opt_p $opt_v $opt_u $file\n"

# if(($#ARGV + 1) != 3)
# {
#     print STDERR usage();
#     exit 1;
# }

# my $file = $ARGV[0];
# my $username = $ARGV[1];
# my $passwd = $ARGV[2];

# print "${file} ${username}\n";

# my $foo = new Apache::Htpasswd($file);

# exit !$foo->htCheckPassword($username,$passwd);
