#!/usr/bin/env perl

use strict;
use warnings;
use Apache::Htpasswd;

sub usage(){
    return "${0} FILE USERNAME PASSWORD\n";
}

if(($#ARGV + 1) != 3)
{
    print STDERR usage();
    exit 1;
}

my $file = $ARGV[0];
my $username = $ARGV[1];
my $passwd = $ARGV[2];

print "${file} ${username}\n";

my $foo = new Apache::Htpasswd($file);

exit !$foo->htCheckPassword($username,$passwd);
