#!/usr/bin/env perl

use strict;
use warnings;
use Apache::Htpasswd;

use Getopt::Std;

sub usage(){
    return "${0} [-s] [-v] [-p PASSWORD] -u USERNAME FILE\n";
}

our($opt_s, $opt_v, $opt_p, $opt_u);

if(!getopts('svp:u:'))
{
    print STDERR usage();
    exit 1;
}

my $file = $ARGV[0];
my $username = $opt_u;

if(!(defined $file) || !(defined $username)) {
    print STDERR usage();
    exit 1;
}

my $passwd = $opt_p;

my $foo = new Apache::Htpasswd($file, UseMD5 => 1);

# verify
if($opt_v)
{
    my $errcode = !$foo->htCheckPassword($username,$passwd);

    if($errcode)
    {
        print STDERR "Password is wrong!\n";
        exit $errcode;
    }

    exit 0
}

exit 1
